tosca_definitions_version: tosca_simple_yaml_1_3

imports:
- sdl-vuln.yaml

node_types:
  sdl.Software:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      ssh_user:
        type: string
        description: The username that will be used to connect to the created VM
      ssh_key_file:
        type: string
        description: Path to the local SSH private key file that will be used for the ssh connection to the VM
    capabilities:
      vulnerability:
        type: sdl.capabilities.VulnerabilityContainer
