tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - root-types/sdl-software.yaml

node_types:
  sdl.Software.WebServer:
    derived_from: sdl.Software

  sdl.Software.Openstack.DockerContainer:
    derived_from: sdl.Software

  sdl.Software.Openstack.DockerContainer.TomcatWebServer:
    derived_from: sdl.Software.Openstack.DockerContainer
    properties:
      cloud:
        type: string
        description: The Openstack project of the VM hosting this container
      name:
        type: string
        description: The name of the Openstack VM hosting this container
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          ssh_user: { value: { get_property: [ SELF, ssh_user ] }, type: string }
          ssh_key_file: { value: { get_property: [ SELF, ssh_key_file ] }, type: string }
        operations:
          create:
            implementation:
              primary: ../playbooks/install-docker-container-tomcatwebserver.yaml

  sdl.Software.WebServer.TomcatWebServer:
    derived_from: sdl.Software.WebServer
    attributes:
      site_config_dir:
        type: string
        description: Location of tomcat configs
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          ssh_user: { value: { get_property: [ SELF, ssh_user ] }, type: string }
          ssh_key_file: { value: { get_property: [ SELF, ssh_key_file ] }, type: string }
        operations:
          create:
            implementation:
              primary: ../playbooks/install-tools-to-victim-vm.yaml

  sdl.Software.WebServer.ApacheWebServer:
    derived_from: sdl.Software.WebServer
    attributes:
      site_config_dir:
        type: string
        description: Location of apache configs
#    interfaces:
#      Standard:
#        type: tosca.interfaces.node.lifecycle.Standard
#        inputs:
#          ssh_user: { value: { get_property: [ SELF, ssh_user ] }, type: string }
#          ssh_key_file: { value: { get_property: [ SELF, ssh_key_file ] }, type: string }
#        operations:
#          create:
#            implementation:
#              primary: ../playbooks/install-tools-to-victim-vm.yaml
#          delete:
#            implementation:
#              primary: ../playbooks/uninstall.yaml

#relationship_types:
#  my.relationships.NginxSiteHosting:
#    derived_from: tosca.relationships.HostedOn
#    interfaces:
#      Configure:
#        operations:
#          post_configure_target:
#            inputs:
#              marker: { value: { get_attribute: [ TARGET, host, id ] }, type: string }
#              ssh_user: { value: { get_property: [ SOURCE, ssh_user ] }, type: string }
#              ssh_key_file: { value: { get_property: [ SOURCE, ssh_key_file ] }, type: string }
#            implementation:
#              primary: playbooks/reload.yaml
