tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - sdl-capability.yaml

node_types:
  sdl.vulnerabilities:
    derived_from: tosca.nodes.Root
    capabilities:
      exploiting_host:
        type: sdl.capabilities.Exploitable
        description: The adversary node which should able to exploit the vulnerability
    requirements:
      - vulnerable_host:
          capability: sdl.capabilities.VulnerabilityContainer
